title: this is my blog
author: Camille Peigne
email: camille.peigne@opendeusto.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome on my blog.
theme: minima

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
